---
on:
  push:
  workflow_dispatch:
concurrency:
  group: "${{github.repository}}-${{ github.ref_name }}"
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  qa:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
      - run: bun install --frozen-lockfile
      - run: bun run lint
      - run: bun run test
