---
on:
  push:
  workflow_dispatch:
concurrency:
  group: "${{github.repository}}-${{ github.ref_name }}"
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/bake-action@v5
        with:
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
      - run: docker compose build ci
      - run: docker compose run --rm ci lint --debug
      - run: docker compose run --rm ci test
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v1
